name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}

      - name: Install the project dependencies
        run: uv sync

      - uses: pre-commit/action@v3.0.1

      - name: Check for changes
        id: git-check
        run: |
          if git diff --exit-code; then
            echo "No changes detected."
          else
            echo "Changes detected!"
            echo "::set-output name=changes_detected::true"
            git diff
          fi

      - name: Fail if changes are detected
        if: steps.git-check.outputs.changes_detected == 'true'
        run: exit 1
        shell: bash
