name: PR Task Adder

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  
jobs:
  add_tasks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add tasks to PR
      uses: actions/github-script@v7
      with:
        script: |
          const issueNumber = context.issue.number;
          const message = `
            Great job making a new implementation!

            Here are some tasks to complete before merging this PR:

            ### Task List for all Jupyter Notebooks
            - [ ] In natural language, explain your understanding of the solution.
            - [ ] In mathematical language, document all implementations of all equations in the same notation as the source paper.
                  Preferably you would do this in the functions docstrings, and cite the equation number in the paper.
                  If it's a single line expression you can instead add a comment in the code.
            - [ ] Make sure the jupyter notebook is importable. This means that all code which is not in functions, in the synced python
                  file, should be inactive.
            `;
          github.rest.issues.createComment({
            issue_number: issueNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
